[package]
name = "steel-rc"
edition = "2021"
version.workspace = true
license = "MIT OR Apache-2.0"
description = "Biased reference counting implementation for steel"
repository = "https://github.com/mattwparas/steel"

[dependencies]
parking_lot = "0.12"
rustc-hash = "2.1.1"
dashmap = "6.1.0"
