[package]
name = "xtask"
edition = "2021"
version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
which = "7.0.0"

[package.metadata.dist]
dist = false
