[package]
name = "cargo-steel-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.15.3"
home = "0.5.9"

# Keeps the MSRV at v1.70.0
cargo-platform = "=0.1.7"
