[book]
authors = ["mattwparas", "fominok"]
language = "en"
src = "src"
title = "The Steel Book"

# [preprocessor.pagetoc]
# [output.html]
# additional-css = ["theme/pagetoc.css"]
# additional-js  = ["theme/pagetoc.js"]
