[book]
authors = ["mattwparas"]
language = "en"
multilingual = false
src = "src"
title = "Steel"

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]